name: Continuous Translation

on: 
  repository_dispatch:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Tronenergize/OpenAI-Continuous-Translator@master
      with:
          git_repo_url: https://github.com/Tronenergize/TronEnergize-API
          api_key: ${{ secrets.OPENAI_API_KEY }}
          target_language: 'Russian'
    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.1
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
